In [2]:
pip install tensorflow


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 189.3/189.3 MB 4.3 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 409.3/409.3 kB 1.3 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.8/440.8 kB 1.7 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.5/126.5 kB 9.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 7.6 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 3.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 6.5 MB/s eta 0:00:0000:0100:01m
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.0/9.0 MB 6.9 MB/s eta 0:00:0000:0100:01m
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 4.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.6/20.6 MB 6.2 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.8/181.8 kB 4.5 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [3]:
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.utils import to_categorical

# 載入並預處理數據
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(-1, 28, 28, 1) / 255.0  # 正規化像素值到 [0, 1]
x_test = x_test.reshape(-1, 28, 28, 1) / 255.0
y_train = to_categorical(y_train, num_classes=10)  # 將標籤轉換成獨熱編碼
y_test = to_categorical(y_test, num_classes=10)

# 建立模型
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

# 編譯模型
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# 訓練模型
model.fit(x_train, y_train, epochs=5, batch_size=64, validation_split=0.1)

# 評估模型
test_loss, test_acc = model.evaluate(x_test, y_test)
print(f"Test accuracy: {test_acc}")


11490434/11490434 [==============================] - 2s 0us/step
Epoch 1/5
844/844 [==============================] - 6s 7ms/step - loss: 0.1983 - accuracy: 0.9408 - val_loss: 0.0686 - val_accuracy: 0.9818
Epoch 2/5
844/844 [==============================] - 5s 6ms/step - loss: 0.0623 - accuracy: 0.9809 - val_loss: 0.0512 - val_accuracy: 0.9857
Epoch 3/5
844/844 [==============================] - 6s 7ms/step - loss: 0.0400 - accuracy: 0.9874 - val_loss: 0.0468 - val_accuracy: 0.9873
Epoch 4/5
844/844 [==============================] - 5s 6ms/step - loss: 0.0282 - accuracy: 0.9913 - val_loss: 0.0493 - val_accuracy: 0.9875
Epoch 5/5
313/313 [==============================] - 0s 1ms/step - loss: 0.0438 - accuracy: 0.9852
Test accuracy: 0.9851999878883362


In [5]:
import numpy as np

# 加載 .npz 文件
data = np.load('/Users/lvhongxiang/Downloads/mnist.npz')

# 逐個讀取數組
array1 = data['array1_name']
array2 = data['array2_name']

# 可以使用讀取到的數組進行後續操作
print(array1)
print(array2)

# 關閉文件
data.close()


KeyError: 'array1_name is not a file in the archive'

In [7]:
import numpy as np

# 加載 .npz 文件
data = np.load('/Users/lvhongxiang/Downloads/mnist.npz')

# 查看文件中包含的所有數組名稱
print(data.files)

# 根據文件中的數組名稱進行讀取
if 'array1_name' in data:
    array1 = data['array1_name']
    print(array1)
else:
    print("array1_name not found in the file.")

if 'array2_name' in data:
    array2 = data['array2_name']
    print(array2)
else:
    print("array2_name not found in the file.")

# 關閉文件
data.close()


['x_test', 'x_train', 'y_train', 'y_test']
array1_name not found in the file.
array2_name not found in the file.


In [8]:
import numpy as np

# 加載 .npz 文件
data = np.load('/Users/lvhongxiang/Downloads/mnist.npz')

# 查看文件中包含的所有數組名稱
print(data.files)

# 根據文件中的數組名稱進行讀取
if 'x_train' in data:
    x_train = data['x_train']
    print(x_train)
else:
    print("x_train not found in the file.")

if 'y_train' in data:
    y_train = data['y_train']
    print(y_train)
else:
    print("y_train not found in the file.")

# 關閉文件
data.close()


['x_test', 'x_train', 'y_train', 'y_test']
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
[5 0 4 ... 5 6 8]
